# Generated by Django 5.0.1 on 2024-02-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPNetwork',
            fields=[
                ('net_id', models.AutoField(primary_key=True, serialize=False)),
                ('net_prefix', models.CharField(max_length=18)),
                ('net_description', models.TextField(blank=True)),
                ('net_createdate', models.DateTimeField(auto_now_add=True)),
                ('net_editdate', models.DateTimeField(auto_now=True)),
                ('net_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipnetapp.ipnetwork')),
            ],
        ),
    ]
