# Generated by Django 5.0.1 on 2024-03-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipnetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_prefix', models.CharField(max_length=18)),
                ('net_description', models.TextField()),
                ('net_createdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'old_db_deleted_networks',
            },
        ),
        migrations.AlterField(
            model_name='ipnetwork',
            name='net_description',
            field=models.CharField(max_length=100),
        ),
    ]
