# Generated by Django 5.0.1 on 2024-03-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipnetapp', '0003_deletednetwork_deleted_at_deletednetwork_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipnetwork',
            name='net_prefix',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
