# Generated by Django 5.0.1 on 2024-04-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipnetapp', '0004_alter_ipnetwork_net_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipnetwork',
            name='net_prefix',
            field=models.CharField(max_length=18),
        ),
    ]
