# Generated by Django 5.0.1 on 2024-04-06 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipnetapp', '0007_alter_ipnetwork_net_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('ip_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_add', models.CharField(max_length=18)),
                ('ip_description', models.CharField(max_length=100)),
                ('ip_createdate', models.DateTimeField(auto_now_add=True)),
                ('ip_editdate', models.DateTimeField(auto_now=True)),
                ('ip_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipnetapp.ipaddress')),
            ],
        ),
    ]
