# Generated by Django 5.0.1 on 2024-04-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipnetapp', '0008_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipnetapp.ipnetwork'),
        ),
    ]
