# Generated by Django 5.0.1 on 2024-04-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('nd_id', models.AutoField(primary_key=True, serialize=False)),
                ('nd_city', models.CharField(max_length=100)),
                ('nd_address', models.CharField(max_length=255)),
                ('nd_name', models.CharField(max_length=100)),
                ('nd_contact', models.CharField(max_length=255)),
                ('nd_description', models.TextField()),
                ('nd_rack_num', models.PositiveIntegerField()),
                ('nd_rack_unit', models.PositiveIntegerField()),
                ('nd_rack_type', models.CharField(max_length=50)),
                ('nd_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eqapp.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('hw_id', models.AutoField(primary_key=True, serialize=False)),
                ('hw_ip', models.CharField(max_length=18)),
                ('hw_vendor', models.CharField(max_length=100)),
                ('hw_model', models.CharField(max_length=100)),
                ('hw_hostname', models.CharField(max_length=255)),
                ('hw_int_type', models.CharField(max_length=50)),
                ('hw_int_num', models.PositiveIntegerField()),
                ('hw_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eqapp.device')),
                ('hw_rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eqapp.rack')),
            ],
        ),
    ]
