# Generated by Django 5.0.1 on 2024-04-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqapp', '0002_alter_rack_nd_rack_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='nd_rack_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='nd_rack_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
