# Generated by Django 5.0.1 on 2024-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqapp', '0003_alter_rack_nd_rack_num_alter_rack_nd_rack_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='nd_rack_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
